import io.testgrid.listeners.TestListener;
import io.testgrid.listeners.RetryFailedTestCases;
import io.testgrid.tg;
import org.testng.annotations.*;
import app.getxray.xray.testng.annotations.XrayTest;
import io.testgrid.enums.ComparisonType;
import org.json.JSONObject;
import io.testgrid.enums.Direction;
import io.testgrid.enums.Size;
import io.testgrid.enums.Buttons;
import static io.testgrid.baseClass.driver;
import org.openqa.selenium.*;
import static io.testgrid.enums.KeyboardKeys.*;
import org.openqa.selenium.support.ui.Select;
import java.net.*;
import java.util.*;
import java.io.*;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.Test;

@Listeners(TestListener.class);
public class case1 {

	@Test(retryAnalyzer = RetryFailedTestCases.class)
	public void case1() {
		tg.openBrowser();
		tg.wait("ele_firstname350", ComparisonType.IS_VISIBLE, 10);
		tg.click("ele_firstname350", 1);
		tg_String var_fname = "test";
		tg.type("ele_firstname350", var_fname);
		tg.wait("ele_lastname015", ComparisonType.IS_CLICKABLE, 10);
		tg.click("ele_lastname015", 1);
		tg.type("ele_lastname015", "#TGITVAR.name");
		tg_String var_email = "";
		var_email = tg.saveToVariable("#TGITVAR.email", var_email);
		tg.writeToCSV("var_email", var_email, "");
		// [DISABLED] tg_String var_email = "testgrid@gmail.com";
		tg.click("ele_nameexampl862", 1);
		tg.type("ele_nameexampl862", var_email);
		tg.click("ele_genderradi912", 1);
		tg_int var_mobilenum = 1234567890;
		tg.click("ele_mobilenumb016", 1);
		tg.type("ele_mobilenumb016", var_mobilenum);
		tg.check.isVisible("ele_mobilenumb016");
		tg.check.isEqualTo(var_mobilenum,"1234567890");
		tg.check.isNotEqualTo(var_mobilenum,"1325");
		tg.check.isGreaterThanOrEqualTo(var_mobilenum,"1234665");
		tg.check.isGreaterThan(var_mobilenum,"123");
		tg.check.isLessThan(var_mobilenum,"1234567891");
		tg.check.isLessThanOrEqualTo(var_mobilenum,"1234567891");
		tg.check.isOn("ele_genderradi912");
		tg.check.isEnabled("ele_genderradi912");
		tg.check.isSelected("ele_genderradi912");
		tg.check.isClickable("ele_firstname350");
		tg.click("ele_dateofbirt356", 1);
		tg.wait("ele_januaryfeb237", ComparisonType.IS_CLICKABLE, 10);
		tg.click("ele_januaryfeb237", 1);
		tg.selectDropdownByIndex("ele_januaryfeb237",10);
		tg.wait("ele_selecttgwe374", ComparisonType.IS_CLICKABLE, 10);
		tg.click("ele_selecttgwe374", 1);
		tg.selectDropdownByValue("ele_selecttgwe374","2004");
		tg.click("ele_divtgwebco217", 1);
		tg.wait("ele_subjectsin378", ComparisonType.IS_CLICKABLE, 10);
		tg.click("ele_subjectsin378", 1);
		tg.type("ele_subjectsin378", "mat");
		tg.pressKey(ENTER, 1);
		tg.type("ele_subjectsin378", "computer sci");
		tg.pressKey(ENTER, 1);
		tg.hoverOverElement("ele_svgtgwebco119");
		tg.click("ele_svgtgwebco119", 1);
		tg.openNewTab();
		tg.navigateToUrl("https://www.saucedemo.com/");
		tg.pageLoadStart("saucelab");
		tg.wait("ele_username341", ComparisonType.IS_CLICKABLE, 10);
		tg.type("ele_username341", "standard_user");
		tg.click("ele_password779", 1);
		tg.type("ele_password779", "secret_sauce");
		tg.click("ele_loginbutto213", 1);
		tg.tapByImage("ele_saucelabsb752", 0.65);
		tg.click("ele_addtocart219", 1);
		tg.click("ele_backtoprod511", 1);
		tg.click("ele_addtocart551", 1);
		tg.click("ele_addtocart960", 1);
		tg.click("ele_addtocart139", 1);
		tg.click("ele_addtocart858", 1);
		tg.click("ele_shoppingca376", 1);
		tg.scrollToElement("ele_checkout491", Direction.DOWN);
		tg.swipe("ele_shoppingca376", Direction.UP);
		START_CUSTOM_SCRIPT;
		System.out.println("😀😃😄😁😆😅😂🤣😊😇🙂🙃😉😍🥰😘😗😙😚😋😜😝😛🤑🤗🤔🤭🤫🤥😶😐😑😬😴😪😵🤯🥳😎🤓🧐🤠🥶🥵😱😨😰😥😓🤤😢😭😤😠😡🤬🤡👻💀☠️👽👾🤖🎃😺😸😹😻😼😽🙀😿😾🔥💥✨⚡🌟🌈☀️🌙⭐🌍🌎🌏🍎🍔🍕🍟🍩🍫🍿🍉🍓🍒🍇🥭🍌🍍🥥🥝🍑🍆🥕🌽🥦🍗🍖🥓🍤🍣🍱🍜🍝🍕🍰🎂🍪🍷🍺☕🥤🚗🏎️🚀✈️🛸🚲🛵🏍️🛶⚓🚦🗺️🏁⚽🏀🏈⚾🎾🏐🏉🎱🏓🥊🥋🎮🎲🎯🎳🎼🎵🎶🎤🎧🎸🥁🎹🎻📱💻🖥️⌨️🖱️🖨️📷📸📹🎥📺📻📡💡🔦🕯️📚📖📄📊📈📉📌📍✂️🖊️🖋️✏️📝💼📁📂🗂");
		END_CUSTOM_SCRIPT;
		tg.printPageSource();
		tg.setBrowserResolution("900", "1200");
		tg.pageLoadEnd("saucelab");
		tg.printLogs("oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo");
		// [DISABLED] tg.switchToTab(0);
		// [DISABLED] tg_String var_address = "";
		// [DISABLED] var_address = tg.saveToVariable("1212, x building, y street, z city", var_address);
		// [DISABLED] tg.click("ele_currentadd096", 1);
		// [DISABLED] tg.type("ele_currentadd096", var_address);
		tg.close();
	}
}